### PR TITLE
Optional number formatting function

### PR DESCRIPTION
**Pull request by nbonamy**
Hello,

thanks for the great package. I needed to use this to format currency value hence with a fixed number of decimals.

I added a numberFormatter optional parameter which defaults to `.toString` hence preserving backwards compatibility.

Also added a 3rd example with `.toFixed(6)`.

- `npm run lint`: OK
- `npm run format`: OK

Thanks

### CODE REVIEW

**Comment by nbonamy** [comment]
Also added ability for initialNumber to be zero

**Comment by der-Lehmann** [comment]
Hi,

thanks for your pull request.

In my opinion, formatting the number should better be handled outside of the `numberFlip` class before it is passed into the `setNumber` function. Leaving that responsibility to the consumer of the package. Therefore I decided not to merge the changes.

But again, thanks for your pull request, this has been the first one I received.

Best regards
Lars

**Comment by nbonamy** [comment]
Understand but the problem is that formatting cannot be done outside as value types are number and not string thus losing any formatting that would have been done before.

**Comment by der-Lehmann** [comment]
You are right, I did not think about that.

**Comment by der-Lehmann** [comment]
I just updated the package on npm.

Best regards
Lars

**Pull request merged**
